DepremProje/Models/Talep.cs
using System.ComponentModel.DataAnnotations;

namespace DepremProje.Models
{
    public class Talep
    {

        [Key]
        public int TalepId { get; set; }
        public string KisiTC { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public string KisiDogumTarihi { get; set; }

        public int SehirId { get; set; }
        public virtual Sehir Sehir { get; set; }


        public int IlceId { get; set; }
        public virtual Ilce Ilce { get; set; }

        public string TalepAcikAdresi { get; set; }

        public int MalzemeId { get; set; }
        public virtual Malzeme Malzeme { get; set; }
        public bool Status { get; set; }

    }
}

DepremProje/Controllers/TalepController.cs
using DepremProje.Models;
using DepremProje.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DepremProje.Controllers
{
    public class TalepController : Controller
    {

		TalepRepository talepRepository;
        Context c;
		public TalepController(TalepRepository _talepRepository,Context _c)
		{
			talepRepository = _talepRepository;
            c = _c;
		}
		public IActionResult Index()
        {
            return View(talepRepository.TList());
        }
        [HttpGet]
        public IActionResult TalepEkle()
        {
            List<SelectListItem> values1 = (from x in c.Sehirs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.SehirAdi,
                                               Value = x.SehirId.ToString()
                                           }).ToList();

            ViewBag.v1 = values1;

            List<SelectListItem> values2 = (from y in c.Ilces.ToList()
                                            select new SelectListItem
                                            {
                                                Text = y.IlceAdi,
                                                Value = y.IlceId.ToString()
                                            }).ToList();

            ViewBag.v2 = values2;

            List<SelectListItem> values3 = (from z in c.Malzemes.ToList()
                                            select new SelectListItem
                                            {
                                                Text = z.MalzemeAdi,
                                                Value = z.MalzemeId.ToString()
                                            }).ToList();

            ViewBag.v3 = values3;
            return View();
        }

        [HttpPost]
        public IActionResult TalepEkle(Talep t)
        {

            talepRepository.TAdd(t);
            return RedirectToAction("Index");
        }


        public IActionResult TalepGet(int id)
        {
            var x = talepRepository.TGet(id);
            List<SelectListItem> values1 = (from a in c.Sehirs.ToList()
                                            select new SelectListItem
                                            {
                                                Text = a.SehirAdi,
                                                Value = a.SehirId.ToString()
                                            }).ToList();

            ViewBag.v1 = values1;

            List<SelectListItem> values2 = (from y in c.Ilces.ToList()
                                            select new SelectListItem
                                            {
                                                Text = y.IlceAdi,
                                                Value = y.IlceId.ToString()
                                            }).ToList();

            ViewBag.v2 = values2;

            List<SelectListItem> values3 = (from z in c.Malzemes.ToList()
                                            select new SelectListItem
                                            {
                                                Text = z.MalzemeAdi,
                                                Value = z.MalzemeId.ToString()
                                            }).ToList();

            ViewBag.v3 = values3;
            Talep t = new Talep
            {
                TalepId = x.TalepId,
                KisiAdi = x.KisiAdi,
                KisiSoyadi = x.KisiSoyadi,
                KisiTC = x.KisiTC,
                KisiDogumTarihi = x.KisiDogumTarihi,
                SehirId = x.SehirId,
                IlceId = x.IlceId,
                TalepAcikAdresi = x.TalepAcikAdresi,
                MalzemeId = x.MalzemeId

            };
            return View("TalepGet", t);
        }

        [HttpPost]
        public IActionResult TalepGuncelle(Talep t)
        {
            var x = talepRepository.TGet(t.TalepId);
            x.TalepId = t.TalepId;
            x.KisiAdi = t.KisiAdi;
            x.KisiSoyadi=t.KisiSoyadi;
            x.KisiTC = t.KisiTC;
            x.KisiDogumTarihi = t.KisiDogumTarihi;
            x.SehirId = t.SehirId;
            x.IlceId = t.IlceId;
            x.TalepAcikAdresi=t.TalepAcikAdresi;
            x.MalzemeId = t.MalzemeId;
            x.Status = true;
            talepRepository.TUpdate(x);

            return RedirectToAction("Index");
        }

        public IActionResult TalepSil(int id)
        {
           // talepRepository.TDelete(new Talep { TalepId = id });
            var x = talepRepository.TGet(id);
            x.Status = false;
            talepRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

DepremProje/Views/Talep/Index.cshtml
@model List<DepremProje.Models.Talep>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1> Talep Listesi</h1>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kisi Adi</th>
        <th>Kisi Soyadi</th>
        <th>TC</th>
        <th>Kisi Dogum Tarihi</th>
        <th>Talep Sehiri</th>
        <th>Talep Ilcesi</th>
        <th>Talep Acik Adresi</th>
        <th>Status</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.TalepId</td>
            <td>@x.KisiAdi</td>
            <td>@x.KisiSoyadi</td>
            <td>@x.KisiTC</td>
            <td>@x.KisiDogumTarihi</td>
            <td>@x.SehirId</td>
            <td>@x.IlceId</td>
            <td>@x.TalepAcikAdresi</td>
            <td>@x.Status</td>
            <td><a href="/Talep/TalepGet/@x.TalepId/" class="btn btn-success">Update</a></td>
            <td><a href="/Talep/TalepSil/@x.TalepId" class="btn btn-danger">Delete</a></td>
        </tr>
    }

</table>
<a href="/Talep/TalepEKle/" class="btn btn-primary">Talep Ekle</a>

DepremProje/Views/Talep/TalepEkle.cshtml
@model DepremProje.Models.Talep
@{
    ViewData["Title"] = "TalepEkle";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1>Talep Ekle</h1>

<br />
@using (Html.BeginForm("TalepEkle", "Talep", FormMethod.Post))
{
    @Html.Label("Ad ")
    @Html.TextBoxFor(x=>x.KisiAdi,new{@class="form-control"} )
    @Html.Label("SoyAd ")
    @Html.TextBoxFor(x=>x.KisiSoyadi,new{@class="form-control"} )

    @Html.Label("Tc ")
    @Html.TextBoxFor(x=>x.KisiTC,new{@class="form-control"} )

    @Html.Label("Doğum Tarihi ")
    @Html.TextBoxFor(x=>x.KisiDogumTarihi,new{@class="form-control"} )

 
    <br />
    @Html.LabelFor(x=>x.Sehir.SehirAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.SehirId,(List<SelectListItem>)ViewBag.v1,  new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x=>x.Ilce.IlceAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.IlceId,(List<SelectListItem>)ViewBag.v2,  new { @class = "form-control" })
    <br />

    @Html.LabelFor(x=>x.Malzeme.MalzemeAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.MalzemeId,(List<SelectListItem>)ViewBag.v3,  new { @class = "form-control" })
    <br />

    @Html.Label("Açık Adres")
    @Html.TextAreaFor(x=>x.TalepAcikAdresi,new{@class="form-control"} )
    <br />
   


    <button class="btn btn-info">Kaydet</button>
}

DepremProje/Views/Talep/TalepGet.cshtml
@model DepremProje.Models.Talep
@{
    ViewData["Title"] = "TalepGet";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

@using (Html.BeginForm("TalepGuncelle", "Talep", FormMethod.Post))
{
    @Html.Label("ID ")
    @Html.TextBoxFor(x=>x.TalepId,new{@class="form-control"} )
    <br />
    @Html.Label("Ad ")
    @Html.TextBoxFor(x=>x.KisiAdi,new{@class="form-control"} )
    <br />
    @Html.Label("SoyAd ")
    @Html.TextBoxFor(x=>x.KisiSoyadi,new{@class="form-control"} )
    <br />
    @Html.Label("Tc ")
    @Html.TextBoxFor(x=>x.KisiTC,new{@class="form-control"} )
    <br />
    @Html.Label("Doğum Tarihi ")
    @Html.TextBoxFor(x=>x.KisiDogumTarihi,new{@class="form-control"} )


    <br />
    @Html.LabelFor(x=>x.Sehir.SehirAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.SehirId,(List<SelectListItem>)ViewBag.v1,  new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x=>x.Ilce.IlceAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.IlceId,(List<SelectListItem>)ViewBag.v2,  new { @class = "form-control" })
    <br />

    @Html.LabelFor(x=>x.Malzeme.MalzemeAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.MalzemeId,(List<SelectListItem>)ViewBag.v3,  new { @class = "form-control" })
    <br />

    @Html.Label("Açık Adres")
    @Html.TextAreaFor(x=>x.TalepAcikAdresi,new{@class="form-control"} )
    <br />



    <button class="btn btn-info">Kaydet</button>
}