DepremProje/Models/Arac.cs
namespace DepremProje.Models
{
    public class Arac
    {
        public int AracId { get; set; }
        public string AracPlaka{ get; set; }
        public string AracOzellikleri { get; set; }
        
    }
}

DepremProje/Controllers/AracController.cs
using DepremProje.Models;
using DepremProje.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DepremProje.Controllers
{
    public class AracController : Controller
    {
        AracRepository aracRepository;
        Context context;

        public AracController(AracRepository _aracRepository, Context _context)
        {
            aracRepository = _aracRepository;
            context = _context;
        }

        public IActionResult Index()
        {
            return View(aracRepository.TList());
        }

        [HttpGet]
        public IActionResult AracEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AracEkle(Arac a)
        {
            aracRepository.TAdd(a);
            return RedirectToAction("Index");
        }

        public IActionResult AracGet(int id)
        {
            var x = aracRepository.TGet(id);
            return View("AracGet",x);
        }

        [HttpPost]
        public IActionResult AracGuncelle(Arac a)
        {
            var x = aracRepository.TGet(a.AracId);
            x.AracId = a.AracId;
            x.AracPlaka = a.AracPlaka;
            x.AracOzellikleri = a.AracOzellikleri;
            aracRepository.TUpdate(x);
            return RedirectToAction("Index");
        }

        public IActionResult AracSil(int id)
        {
            aracRepository.TDelete(new Arac { AracId = id });
            return RedirectToAction("Index");
        }
    }
}

DepremProje/Views/Arac/AracEkle.cshtml
@model DepremProje.Models.Arac
@{
    ViewData["Title"] = "AracEkle";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1>Arac Ekle</h1>

<br />
@using (Html.BeginForm("AracEkle", "Arac", FormMethod.Post))
{
    @Html.LabelFor(x=>x.AracPlaka)
    @Html.TextBoxFor(x=>x.AracPlaka,new{@class="form-control"} )
    @* @Html.ValidationMessageFor(x=>x.KategoriAdi,"",new {@style="color:red"})*@
    <br />
    @Html.LabelFor(x=>x.AracOzellikleri)
    @Html.TextBoxFor(x=>x.AracOzellikleri,new{@class="form-control"} )
    <br />
    <button class="btn btn-info">Kaydet</button>
}

DepremProje/Views/Arac/AracGet.cshtml
@model DepremProje.Models.Arac
@{
    ViewData["Title"] = "AracGet";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

@using (Html.BeginForm("AracGuncelle", "Arac", FormMethod.Post))
{
    @Html.LabelFor(x=>x.AracId)
    @Html.TextBoxFor(x=>x.AracId,new{@class="form-control"} )
    @Html.LabelFor(x=>x.AracPlaka)
    @Html.TextBoxFor(x=>x.AracPlaka,new{@class="form-control"} )
    @* @Html.ValidationMessageFor(x=>x.KategoriAdi,"",new {@style="color:red"})*@
    <br />
    @Html.LabelFor(x=>x.AracOzellikleri)
    @Html.TextBoxFor(x=>x.AracOzellikleri,new{@class="form-control"} )
    <br />
    <button class="btn btn-info">Kaydet</button>
}

DepremProje/Views/Arac/Index.cshtml
@model List<DepremProje.Models.Arac>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1>Burası Arac listesi</h1>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Araç Plaka</th>
        <th>Araç Özellikler</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.AracId</td>
            <td>@x.AracPlaka</td>
            <td>@x.AracOzellikleri</td>
            <td><a href="/Arac/AracSil/@x.AracId" class="btn btn-danger">Delete</a></td>
            <td><a href="/Arac/AracGet/@x.AracId" class="btn btn-warning">Guncelle</a></td>
        </tr>
    }

</table>
<a href="/Arac/AracEkle" class="btn btn-primary">Arac Ekle</a>