DepremProje/Models/Malzeme.cs
using System.ComponentModel.DataAnnotations;

namespace DepremProje.Models
{
    public class Malzeme
    {
        [Key]
        public int MalzemeId { get; set; }
        public string MalzemeAdi { get; set; }
        public string MalzemeAciklamasi { get; set; }
        public string MalzemeStokAdedi { get; set; }

        public int KategoriId { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}

DepremProje/Controllers/MalzemeController.cs
using DepremProje.Models;
using DepremProje.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DepremProje.Controllers
{
    public class MalzemeController : Controller
    {
        MalzemeRepository malzemeRepository;
        Context c;

        public MalzemeController(MalzemeRepository _malzemeRepository, Context _c)
        {
            malzemeRepository = _malzemeRepository;
            c = _c; 
        }

        public IActionResult Index()
        {
            return View(malzemeRepository.TList());
        }

        [HttpGet]
        public IActionResult MalzemeEkle()
        {
            List<SelectListItem> values = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAdi,
                                               Value = x.KategoriId.ToString()
                                           }).ToList();

            ViewBag.v1 = values;
            return View();
        }

        [HttpPost]
        public IActionResult MalzemeEkle(Malzeme m)
        {
            
            malzemeRepository.TAdd(m);
            return RedirectToAction("Index");
        }
        public IActionResult MalzemeGet(int id)
        {
            var x = malzemeRepository.TGet(id);
            List<SelectListItem> values = (from y in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.KategoriAdi,
                                               Value = y.KategoriId.ToString()
                                           }).ToList();

            ViewBag.v1 = values;
            Malzeme m = new Malzeme
            {
                MalzemeId = x.MalzemeId,
                MalzemeAdi = x.MalzemeAdi,
                KategoriId = x.KategoriId,
                MalzemeStokAdedi = x.MalzemeStokAdedi,
                MalzemeAciklamasi = x.MalzemeAciklamasi
            };
            return View("MalzemeGet", m);
        }

        [HttpPost]
        public IActionResult MalzemeGuncelle(Malzeme m)
        {
            var x = malzemeRepository.TGet(m.MalzemeId);
            x.MalzemeAdi = m.MalzemeAdi;
            x.KategoriId = m.KategoriId;
            x.MalzemeStokAdedi = m.MalzemeStokAdedi;
            x.MalzemeAciklamasi = m.MalzemeAciklamasi;
            malzemeRepository.TUpdate(x);

            return RedirectToAction("Index");
        }

        public IActionResult MalzemeSil(int id)
        {
            malzemeRepository.TDelete(new Malzeme { MalzemeId = id });
            return RedirectToAction("Index");
        }

    }
}

DepremProje/Views/Malzeme/Index.cshtml
@model List<DepremProje.Models.Malzeme>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1>Malzemeler Listesi</h1>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Malzeme Ad</th>
        <th>Kategori ID</th>
        <th>Stok</th>
        <th>Malzeme Açıklaması</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.MalzemeId</td>
            <td>@x.MalzemeAdi</td>
            <td>@x.KategoriId</td>
            <td>@x.MalzemeStokAdedi</td>
            <td>@x.MalzemeAciklamasi</td>
            <td><a href="/Malzeme/MalzemeSil/@x.MalzemeId" class="btn btn-danger">Delete</a></td>
            <td><a href="/Malzeme/MalzemeGet/@x.MalzemeId" class="btn btn-warning">Guncelle</a></td>
        </tr>
    }

</table>
<a href="/Malzeme/MalzemeEkle/" class="btn btn-primary">Malzeme Ekle</a>

DepremProje/Views/Malzeme/MalzemeEkle.cshtml
@model DepremProje.Models.Malzeme
@{
    ViewData["Title"] = "MalzemeEkle";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

<h1>Malzeme Ekle</h1>

<br />
@using (Html.BeginForm("MalzemeEkle", "Malzeme", FormMethod.Post))
{
    @Html.Label("Malzeme Ad ")
    @Html.TextBoxFor(x=>x.MalzemeAdi,new{@class="form-control"} )
    @* @Html.ValidationMessageFor(x=>x.KategoriAdi,"",new {@style="color:red"})*@
    <br />
    @Html.LabelFor(x=>x.Kategori.KategoriAdi, new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.KategoriId,(List<SelectListItem>)ViewBag.v1,  new { @class = "form-control" })
    <br />

    @Html.Label("Stok")
    @Html.TextBoxFor(x=>x.MalzemeStokAdedi,new{@class="form-control"} )
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x=>x.MalzemeAciklamasi,new{@class="form-control"} )
    <br />

    <button class="btn btn-info">Kaydet</button>
}

DepremProje/Views/Malzeme/MalzemeGet.cshtml
@model DepremProje.Models.Malzeme

@{
    ViewData["Title"] = "MalzemeGet";
    Layout = "~/Views/Shared/_DepremLayout.cshtml";
}

@using (Html.BeginForm("MalzemeGuncelle", "Malzeme", FormMethod.Post))
{
    @Html.Label("ID ")
    @Html.TextBoxFor(x=>x.MalzemeId,new{@class="form-control"} )
    <br />

    @Html.Label("Malzeme Ad ")
    @Html.TextBoxFor(x=>x.MalzemeAdi,new{@class="form-control"} )
    @* @Html.ValidationMessageFor(x=>x.KategoriAdi,"",new {@style="color:red"})*@
    <br />
    @Html.Label("Kategori ")
    @Html.DropDownListFor(x=>x.KategoriId,(List<SelectListItem>)ViewBag.v1, new {@class="form-control"})
    <br />
    @Html.Label("Stok")
    @Html.TextBoxFor(x=>x.MalzemeStokAdedi,new{@class="form-control"} )
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x=>x.MalzemeAciklamasi,new{@class="form-control"} )
    <br />

    <button class="btn btn-info">Kaydet</button>
}